### ISSUE TITLE
Integrate SCRAM from Authen-SCRAM directly into Authen-SASL?

### ISSUE THREAD

**Issue by Neustradamus** [gbarr/perl-authen-sasl#10]
It will be nice to have a best Authen::SASL with Authen::SCRAM directly.

Thanks in advance.

**Comment by ehuelsmann** [comment]
@gbarr I've released my dist `Authen::SASL::SCRAM` which does exactly what @Neustradamus is asking for, without actually making `Authen::SASL` depend on `Authen::SCRAM`. I think this issue can be closed.

**Comment by ehuelsmann** [comment]
This has been implemented in `Authen::SASL::SCRAM` instead.
